### PR TITLE
Fix some characters stuck. Fix #251

### LINKED ISSUE #251: [BUG] French accent cannot be selected correctly
With the QWERTY Keyboard, if you try sometimes to select the french "e" accent (é or è), it'll print ú or or t with an accent or á and many other strange things. Its append with other accent too.

**How to reproduce the bug** ?
For the moment, I don't really understand when exactly this bug append, but I though it when you type the `a` french accent (à) then you try to write a e french accent (é or è).

For example:
Try to type: `Je vais à l'école` (I'm going to school), it'll work because I don't know.
But try : `Dans les boîtes en métal` (In the metal boxes), it'll write:
`Dans les boîtes en m8tal` because you can't select other thing than 8.

If you write: `î` then you try to put an accent on `e`, it will just print ì or í or ï or something like that.

I'm sorry for these poor information, but I don't know how this app work because I didn't read the code, so I don't know where the problem is exactly and when it's append.

### PR DESCRIPTION
**Pull request by dmitriy-chernysh**
Fix #251 
Fixed issue with caching for mini keyboard views: Getting 'miniKeyboardView' from 'mMiniKeyboardCache' and not from the previously shown layout. It's not related to a specific language.

+ removed mMiniKeyboard!!.mOnKeyboardActionListener is not needed in MyKeyboardView.onLongPress() func. Originally defined in SimpleKeyboardIME class.

How it works now https://youtube.com/shorts/GX2mhKSx910

### CODE REVIEW

File: app/src/main/kotlin/com/simplemobiletools/keyboard/views/MyKeyboardView.kt [hunk 1]
```diff
@@ -1056,7 +1025,9 @@ class MyKeyboardView @JvmOverloads constructor(context: Context, attrs: Attribut
                     )
                     mMiniKeyboardCache[popupKey] = mMiniKeyboardContainer
                 } else {
-                    mMiniKeyboard = keyboardPopupBinding!!.miniKeyboardView
+                    //Using 'miniKeyboardView' from cache
+                    mMiniKeyboard = mMiniKeyboardCache[popupKey]?.let(KeyboardPopupKeyboardBinding::bind)?.miniKeyboardView
```
Comment (tibbi) [inline app/src/main/kotlin/com/simplemobiletools/keyboard/views/MyKeyboardView.kt:1029]: simplify this line please, theres way too many things going on. Also avoid adding useless comments.

**Comment by tibbi** [comment]
ok thanks, should be good
